// <auto-generated />
namespace FilmRanking.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class m2mactorsFilms : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(m2mactorsFilms));
        
        string IMigrationMetadata.Id
        {
            get { return "201710170850141_m2m actorsFilms"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
